apiVersion: apps/v1
kind: Deployment
metadata:
  name: claim-service-deployment
  labels:
    app: claim-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: claim-service
  template:
    metadata:
      labels:
        app: claim-service
    spec:
      serviceAccountName: claims-app-sa
      containers:
        - name: claim-service
          image: ${IMG_URL}
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "300Mi"
              cpu: "250m"
